require:
  - rubocop-katalyst
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - node_modules/**/*
    - vendor/bundle/**/*
  NewCops: enable
